### PR TITLE
Add support for the field "conditionalLogic" for formFields

### LINKED ISSUE #18: Get conditionalLogic for formFields?
Right now can't see how to get conditionalLogic for formFields :(

Pretty sure it does exist, I checked it in docs

I wouldn't even mind helping with PR to speed up the process if you wouldn't mind helping me with pointing out where to do it :)

### PR DESCRIPTION
**Pull request by SilencerWeb**
Fixes #18

### CODE REVIEW

**Review by robmarshall — CHANGES_REQUESTED** [review]
Nice one!

How does GF pass the data? Would you be able to provide an example in the readme?

**Comment by SilencerWeb** [comment]
@robmarshall, basically, `conditionalLogic` is the same as `choices` — it's an object presented as a string

**Comment by robmarshall** [comment]
Cheers!

**Comment by SilencerWeb** [comment]
@robmarshall, what about publishing an update of the package? :)

**Comment by robmarshall** [comment]
Sorted. Thanks for the help!

**Pull request merged**
